[package]
name = 'brickpack-sampleapp'
version = '0.1.1'
authors = ['Antonio Feitosa <antonio.cfc@gmail.com>']
edition = '2018'

[dependencies]
clap = '2.33.1'
http-types = "1.2.0"

[dependencies.brickpack]
git = 'https://github.com/afsec/brickpack'
version = '0.1'
#path = '../brickpack'
